app_identifier "com.coldtank.cards"
team_id ENV["TEAM_ID"]
metadata_path "./fastlane/metadata"
screenshots_path "./fastlane/screenshots"
submit_for_review true
automatic_release false
force true
overwrite_screenshots true
